#!/usr/bin/env php
<?php

// requires monitor enabled in ntp.conf

function fTime($diff) {

    $d[0] = array(60,"minute");
    $d[1] = array(3600,"hour");
    $d[2] = array(86400,"day");

    $w = array();
    $return = "";
    $secondsLeft = $diff;

    for($i=2;$i>-1;$i--)
    {
         $w[$i] = intval($secondsLeft/$d[$i][0]);
         $secondsLeft -= ($w[$i]*$d[$i][0]);
         if($w[$i]!=0)
         {
            $return .= abs($w[$i]) . " " . $d[$i][1] . (($w[$i]>1)?'s':'') ." ";
         }

    }

    return $return;
}


$servers = array();
$output = array();
$fresh_clients = array();
$stale_clients = array();

// args
$shortopts = "h";
$longopts = array("ignore:", "help", "threshold:");
$options = getopt($shortopts, $longopts);
$threshold = "172800"; // two day default
if ( isset($options['threshold']) ) {
	$threshold = $options['threshold'];
}
$ignore = [];
if ( isset($options['ignore']) ) {
	$ignore = (array) $options["ignore"];
}

// help
if ( isset($options['h']) or isset($options['help']) ) {
	$me = basename(__FILE__);
	echo "Usage: $me [ OPTIONS ]
	OPTIONS:
	--ignore <ip address>
	\tClient to ignore. Can be specified multiple times.
	--threshold <seconds>
	\tWarning threshold. Defaults to two days.\n";
    exit(3);
}


function fetch_ntp_servers() {
	$command = 'ntpdc -nc listpeers';
	exec( $command, $output );
	foreach ( $output as $line ) {
		$columns = preg_split( '/\s+/', trim($line) );
		$servers[] = $columns[1];
	}
	return $servers;

}

function fetch_ntp_clients() {
	$command = 'ntpdc -nc monlist';
	exec( $command, $output );
	return $output;

}


// run external commands
$servers = fetch_ntp_servers();
$output = fetch_ntp_clients();


// process clients
foreach ( $output as $line ) {

	// exclude headers
	if ( preg_match("/^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\s/", $line) ) {
		$columns = preg_split( '/\s+/', trim($line) );
		$client = $columns[0];
		$seconds = $columns[8];
	
		// exclude stratum 1 and ignore list
	        if ( !in_array($client, $servers) and !in_array($client, $ignore) ) {
	
			// only clients above threshold
			if ( $seconds > $threshold ) {
	
				// only online clients
				exec("ping -qc1 $client -W 1 2>/dev/null", $pingoutput, $pingreturn);
				if ( $pingreturn == 0 ) {
					$stale_clients += [ $client => $seconds ];
	
				}
	
			} else {
				$fresh_clients[] = $client;
	
			}
	
		}

	}

}

// nagios output
if ( empty($output) ) {
	$return_status = 3;
	print("UNKNOWN: Error fetching ntpdc monlist\n");

} elseif ( empty($fresh_clients) ) {
	$return_status = 1;
	print("WARNING: No known clients.\n");

} elseif ( count($stale_clients) ) {
	$return_status = 1;
	foreach ( $stale_clients as $key => $value) {
		$client = $key;
		$seconds = $value;
		$humantime = fTime($seconds);
		$domain = gethostbyaddr($client);
		print( "$domain stale for $humantime\n" );
	}
	print("\nIf this is ok, add the client to the ignore list (recommended), or restart ntpd to clear all known clients.\n");

} else {
	$return_status = 0;
	$clientcount = count($fresh_clients);
	print("OK: $clientcount known clients.\n");
}

                                                                                                                                                    
exit($return_status);
